modLoader="javafml"
loaderVersion="[51,52)"
license="MIT"
#issueTrackerURL="https://github.com/yourusername/playerswapmod/issues" #optional

[[mods]]
modId="playerswapmod"
version="1.0.0"
displayName="Player Swap Mod"
authors="Oli A."
description='A mod that swaps players positions and inventories periodically.'

[[dependencies.playerswapmod]]
modId="forge"
mandatory=true
versionRange="[51,)"
ordering="NONE"
side="BOTH"

[[dependencies.playerswapmod]]
modId="minecraft"
mandatory=true
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"
